# Generated by Django 2.2.28 on 2023-08-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('Price', models.IntegerField(max_length=10)),
                ('availability', models.IntegerField(max_length=10)),
            ],
        ),
    ]
