# Generated by Django 4.2 on 2023-05-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medicine_Name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('Price', models.CharField(max_length=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('side_effect', models.TextField(max_length=50)),
            ],
        ),
    ]
