# Generated by Django 4.2 on 2023-05-10 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='Medicine_Name',
            new_name='mname',
        ),
    ]
